import type { LegalTranslations } from '../components/LegalDocument';

function defineTranslations(entries: Record<string, string>): LegalTranslations {
  return Object.fromEntries(
    Object.entries(entries).map(([korean, english]) => [korean.replace(/\s+/g, ''), english]),
  );
}

export const privacyTranslations = defineTranslations({
  '오성훈(이하 “운영자”)은 Subnota(이하 “서비스”)를 운영하며, 서비스 제공에 필요한 최소한의 개인정보를 처리합니다. 이 방침은 서비스의 웹사이트, 데스크톱 앱 및 모바일 앱에 적용됩니다.':
    'Oh Seonghun (the “Operator”) operates Subnota (the “Service”) and processes the minimum personal information necessary to provide the Service. This policy applies to the Service website, desktop app, and mobile app.',
  '이 문서는 서비스 이용약관과 구별되는 개인정보 처리 현황 안내입니다. 현재 결제나 유료 플랜은 제공하지 않으며, 결제 기능을 출시하면 관련 처리 내용을 추가하여 이 방침을 갱신합니다.':
    'This document explains how personal information is processed and is separate from the Terms of Service. We do not currently offer payments or paid plans; if payment features are introduced, this policy will be updated with the relevant processing details.',
  '1. 개인정보 처리자와 보호책임자': '1. Data Controller and Privacy Officer',
  '개인정보 처리자': 'Data controller',
  '서비스명': 'Service name',
  '개인정보 보호책임자 및 고충처리 담당': 'Privacy officer and complaints contact',
  '문의처': 'Contact',
  '개인정보 관련 문의, 열람·정정·삭제·처리정지 요청, 계정 삭제 요청 및 개인정보 침해 신고는 위 이메일로 접수할 수 있습니다. 운영자는 요청자의 본인 여부 또는 정당한 대리인 여부를 확인한 뒤 필요한 조치를 합니다.':
    'Privacy questions, requests to access, correct, delete, or suspend processing, account deletion requests, and reports of privacy breaches may be sent to the email address above. The Operator will take the necessary action after verifying the requester’s identity or authority to act on another person’s behalf.',
  '서비스 운영·보안·장애 대응·계정 삭제에 필요한 경우 운영자는 Supabase의 인증 및 관리자 기능을 통해 사용자의 이메일, 사용자 식별자 및 계정 상태를 확인할 수 있습니다. 이는 서비스 운영에 필요한 범위로 제한하며, 광고나 별도의 영업 목적으로 이용하지 않습니다.':
    'When necessary for Service operations, security, incident response, or account deletion, the Operator may check a user’s email, user identifier, and account status through Supabase authentication and administrative functions. This access is limited to what is necessary to operate the Service and is not used for advertising or separate commercial purposes.',
  '2. 개인정보의 처리 목적, 항목 및 법적 근거': '2. Purposes, Categories, and Legal Bases for Processing Personal Information',
  '운영자는 서비스 제공에 필요한 최소한의 범위에서 개인정보를 처리합니다. 현재 별도의 선택적 개인정보 수집·이용, 광고성 이메일 및 마케팅 목적의 개인정보 처리는 하지 않습니다.':
    'The Operator processes personal information only to the minimum extent necessary to provide the Service. We do not currently carry out separate optional collection or use of personal information, promotional email processing, or marketing processing.',
  '처리 구분': 'Processing category',
  '처리하는 항목': 'Categories of information',
  '처리 목적': 'Purpose',
  '법적 근거': 'Legal basis',
  '계정·인증': 'Account and authentication',
  'Supabase Auth 사용자 ID, 이메일 주소, 인증 제공자, 인증 제공자의 사용자 식별자, 계정 상태':
    'Supabase Auth user ID, email address, authentication provider, provider user identifier, and account status',
  '회원가입, 로그인, 본인 식별, 계정 유지, 계정 삭제 및 보안 관리':
    'Sign-up, login, identity verification, account maintenance, account deletion, and security management',
  '개인정보 보호법 제15조제1항제4호(계약의 체결·이행)':
    'Article 15(1)4 of the Personal Information Protection Act (entering into and performing a contract)',
  '메모·일정': 'Memos and schedules',
  '메모 본문, 메모 생성·수정 시각, 캘린더 일정의 제목·시작 시각·종료 시각·메모·완료 상태·색상 및 사용자가 선택한 분류 정보':
    'Memo content, memo creation and modification times, calendar event titles, start and end times, notes, completion status, colors, and categories selected by the user',
  '저장, 동기화, 검색, 일정 관리, 브리핑 및 네트워크 기능 제공':
    'Storage, synchronization, search, schedule management, briefings, and network features',
  '수집함': 'Saved links',
  '사용자가 저장한 웹페이지 URL, 제목, 설명, 썸네일 URL, 추출 텍스트 및 서비스가 생성한 수집함 요약·키워드':
    'Saved webpage URLs, titles, descriptions, thumbnail URLs, extracted text, and saved-link summaries and keywords generated by the Service',
  '웹페이지 저장, 미리보기, 요약, 검색 및 메모와의 연결':
    'Webpage saving, previews, summaries, search, and connections to memos',
  '서비스 생성 결과': 'Service-generated results',
  '요약, 분류, 키워드, 토픽 라벨, 임베딩 벡터, 유사도 및 메모·수집함 간 연결 결과, 데일리 브리핑':
    'Summaries, categories, keywords, topic labels, embedding vectors, similarity scores, connections between memos and saved links, and daily briefings',
  '검색, 연결, 추천, 토픽 지도 및 브리핑 기능 제공':
    'Search, connections, recommendations, topic maps, and briefing features',
  '기술·보안 정보': 'Technical and security information',
  '접속 시각, 요청 경로, 사용자 에이전트, 오류·보안 이벤트, 사용자 ID와 메모 ID 등 운영 로그에 포함될 수 있는 식별자':
    'Access times, request paths, user agents, error and security events, and identifiers that may appear in operational logs, such as user IDs and memo IDs',
  '인증, 보안, 장애 대응, 부정 이용 방지 및 서비스 안정성 확보':
    'Authentication, security, incident response, prevention of misuse, and Service stability',
  '개인정보 보호법 제15조제1항제4호(계약의 체결·이행) 및 제6호(정당한 이익)':
    'Article 15(1)4 (entering into and performing a contract) and 15(1)6 (legitimate interests) of the Personal Information Protection Act',
  '기기 내 데이터': 'On-device data',
  '기기 내 SQLite 데이터베이스에 저장되는 메모·일정·수집함·설정·로컬 임베딩 및 다운로드된 모델 파일':
    'Memos, schedules, saved links, settings, local embeddings, and downloaded model files stored in the device SQLite database',
  '오프라인 이용, 빠른 검색, 기기 설정 유지 및 로컬 임베딩 제공':
    'Offline use, fast search, device settings, and local embedding features',
  '서비스 제공을 위한 계약의 체결·이행': 'Entering into and performing a contract to provide the Service',
  '익명·비식별 통계': 'Anonymous and de-identified statistics',
  '계정 ID·이메일·메모 본문과 연결하지 않는 플랫폼·환경 구분, 기능 이용 통계 및 SDK 요청의 기술 정보':
    'Platform and environment details, feature usage statistics, and technical information from SDK requests that are not linked to account IDs, email addresses, or memo content',
  '서비스 품질과 사용성 개선': 'Improving Service quality and usability',
  '개인정보에 해당하지 않는 범위에서 처리하며, 해당되는 경우 제15조제1항제6호(정당한 이익)':
    'Processed to the extent it is not personal information, or, where applicable, under Article 15(1)6 (legitimate interests)',
  '계정 정보는 이메일 가입 과정에서 이용자가 직접 입력하거나 Google OAuth를 통해 제공받습니다. 메모·일정·수집함 정보는 이용자가 서비스에 입력하거나 저장할 때 생성됩니다. 서비스 생성 결과는 위 입력을 처리하는 과정에서 생성되는 정보입니다.':
    'Account information is entered directly by the user during email sign-up or provided through Google OAuth. Memo, schedule, and saved-link information is created when the user enters or saves it in the Service. Service-generated results are created while processing that input.',
  '현재 서비스에는 선택적 동의로 처리하는 항목이 없습니다. 향후 광고, 마케팅, 연구, 개인화 분석 등 계약 이행과 직접 관련되지 않은 처리를 추가하는 경우에는 목적·항목·보유기간을 분리하여 안내하고 필요한 동의를 별도로 받습니다.':
    'The Service currently has no categories processed on the basis of optional consent. If we add processing not directly related to performing a contract, such as advertising, marketing, research, or personalized analysis, we will separately describe its purpose, categories, and retention period and obtain any required consent.',
  '익명·비식별 통계는 계정·이메일·메모 본문과 연결하지 않는 최소 범위로 운영합니다. 네트워크 요청에 포함될 수 있는 임시 식별자나 접속 정보가 관련 법령상 개인정보로 판단되는 경우에는 서비스 품질 개선을 위한 정당한 이익을 근거로 처리하며, 해당 통계 전송을 차단할 수 있는 방법을 제13항에 안내합니다.':
    'Anonymous and de-identified statistics are limited to the minimum scope and are not linked to accounts, email addresses, or memo content. If temporary identifiers or connection information included in network requests are considered personal information under applicable law, they are processed on the basis of legitimate interests in improving Service quality. Section 13 explains how to block transmission of those statistics.',
  '3. 14세 미만 아동의 개인정보': '3. Personal Information of Children Under 14',
  'Subnota는 만 14세 미만 아동을 주 이용자로 하는 서비스가 아니며, 만 14세 미만 아동의 개인정보를 수집·이용하는 별도의 가입 및 법정대리인 동의 확인 절차를 제공하지 않습니다. 만 14세 미만 이용자는 법정대리인의 도움 없이 가입하거나 이용하지 않아야 합니다.':
    'Subnota is not directed primarily to children under 14 and does not provide a separate sign-up or parental-consent verification process for collecting or using the personal information of children under 14. Users under 14 must not sign up for or use the Service without a legal guardian’s assistance.',
  '운영자가 만 14세 미만 아동의 개인정보가 처리된 사실을 알게 되면 해당 계정과 데이터를 확인하여 지체 없이 삭제하고, 법정대리인이 삭제를 요청하는 경우':
    'If the Operator learns that the personal information of a child under 14 has been processed, the relevant account and data will be identified and deleted without delay. A legal guardian may request deletion at ',
  '으로 접수합니다.': ' by contacting the address above.',
  '법정대리인은 법정대리인임을 확인할 수 있는 범위에서 아동의 개인정보에 대한 열람·정정·삭제·처리정지를 요청할 수 있습니다.':
    'A legal guardian may request access to, correction, deletion of, or suspension of processing of the child’s personal information to the extent necessary to verify the guardianship.',
  '4. 개인정보의 처리 및 보유 기간': '4. Processing and Retention Periods',
  '처리 대상': 'Data subject',
  '보유·이용 기간': 'Retention and use period',
  '삭제 또는 보관 기준': 'Deletion or retention standard',
  '계정·메모·일정·수집함·생성 결과': 'Accounts, memos, schedules, saved links, and generated results',
  '계정 삭제 또는 처리 목적 달성 시까지': 'Until account deletion or the purpose of processing is achieved',
  '계정 삭제 요청 시 서비스 DB와 인증 계정에서 삭제': 'Deleted from the Service database and authentication account when account deletion is requested',
  '기기 내 로컬 데이터': 'Local device data',
  '앱에서 삭제하거나 앱을 제거할 때까지': 'Until deleted in the app or the app is uninstalled',
  '계정 삭제 기능 실행 시 해당 기기의 계정별 데이터와 로컬 임베딩 삭제': 'Deleted from the device, by account, when the account deletion function is used',
  '문의·권리 행사 기록': 'Inquiry and rights-exercise records',
  '문의 및 권리 행사 처리에 필요한 기간': 'The period necessary to handle the inquiry or rights request',
  '처리 완료 후 분쟁·보안·법적 의무에 필요한 범위를 제외하고 지체 없이 삭제': 'Deleted without delay after completion, except to the extent needed for disputes, security, or legal obligations',
  '운영·보안 로그': 'Operational and security logs',
  '보안·장애·부정 이용 대응에 필요한 기간': 'The period necessary for security, incident, and misuse response',
  'Cloud Run, Vercel 및 Supabase의 로그·백업 설정과 제공자 정책에 따른 기간 후 삭제': 'Deleted after the period specified by the log and backup settings and provider policies of Cloud Run, Vercel, and Supabase',
  '외부 AI·임베딩 제공자의 요청 로그': 'Request logs held by external AI and embedding providers',
  '각 제공자의 정책 및 API 프로젝트 설정에 따른 기간': 'The period specified by each provider’s policy and API project settings',
  '운영자는 별도의 요청 원문 로그를 보관하지 않으며, 제공자 측 로그·캐시는 제공자의 삭제·보관 정책 적용': 'The Operator does not retain separate logs of request contents; provider-side logs and caches are subject to the provider’s deletion and retention policies',
  '서비스 데이터의 보유기간을 특정하기 어려운 운영·보안 로그는 위 목적이 달성되거나 보안·분쟁 대응이 끝나는 때까지 보유합니다. 법령에 따라 보존해야 하는 자료가 발생하면 해당 법령, 보존 항목 및 기간에 따라 다른 데이터와 분리하여 보관합니다. 현재 결제·전자상거래 기록은 처리하지 않습니다.':
    'Operational and security logs whose retention period cannot be specified in advance are retained until the purposes above are achieved or security and dispute response is complete. If records must be retained by law, they are stored separately from other data according to the applicable law, categories, and period. We currently do not process payment or e-commerce records.',
  '5. 개인정보의 파기 절차 및 방법': '5. Procedures and Methods for Destroying Personal Information',
  '파기 절차: 보유기간 경과, 처리 목적 달성 또는 계정 삭제 요청으로 파기 사유가 발생하면 운영자가 파기 대상과 범위를 확인하여 파기합니다.':
    'Destruction procedure: When a destruction event occurs because the retention period has expired, the processing purpose has been achieved, or an account deletion has been requested, the Operator identifies the scope and destroys the relevant data.',
  '전자 파일: 복구할 수 없도록 서비스 데이터베이스의 계정·콘텐츠·생성 결과와 Supabase 인증 계정을 삭제합니다. 계정 삭제 API는 사용자별 데이터를 먼저 삭제한 뒤 인증 계정을 삭제합니다.':
    'Electronic files: The Service database accounts, content, generated results, and Supabase authentication account are deleted so they cannot be recovered. The account deletion API deletes user data before deleting the authentication account.',
  '기기 데이터: 앱의 계정 삭제 절차에서 계정별 로컬 콘텐츠·설정·임베딩을 삭제합니다. 별도의 종이 문서는 보관하지 않습니다.':
    'Device data: The account deletion procedure deletes local content, settings, and embeddings by account. No separate paper records are retained.',
  '백업·제공자 로그: 즉시 삭제가 기술적으로 어려운 백업 또는 외부 제공자의 잔여 로그는 해당 보관주기가 끝난 뒤 복구할 수 없는 방법으로 삭제합니다.':
    'Backups and provider logs: Backups or residual logs held by external providers that cannot be deleted immediately for technical reasons are deleted irreversibly after their retention period ends.',
  '6. 개인정보의 제3자 제공': '6. Provision of Personal Information to Third Parties',
  '운영자는 현재 개인정보를 제3자의 독립적인 사업 목적을 위해 판매하거나 제공하지 않습니다. 서비스 제공을 위해 다른 사업자가 운영자의 지시에 따라 처리하는 경우에는 아래의 “처리위탁”으로 구분합니다. 다만 법률에 특별한 규정이 있거나 수사·재판·행정기관의 적법한 요청이 있는 경우에는 법령이 허용하는 범위에서 제공할 수 있습니다. 외부 API 제공자의 자체 보안·악용 방지·제품 개선 처리는 제공자의 약관과 서비스 유형에 따라 달라질 수 있으며, 그 가능성과 거부 방법은 제10항에서 별도로 안내합니다.':
    'The Operator does not currently sell or provide personal information for the independent business purposes of third parties. When another business processes information at the Operator’s direction to provide the Service, it is treated as “outsourcing of processing” below. Information may be provided to the extent permitted by law when required by a specific law or in response to a lawful request from an investigative, judicial, or administrative authority. External API providers may carry out their own security, abuse-prevention, or product-improvement processing depending on their terms and service type; the possibility and opt-out methods are described separately in Section 10.',
  '7. 개인정보 처리업무의 위탁': '7. Outsourcing of Personal Information Processing',
  '운영자는 서비스 제공에 필요한 업무를 다음 수탁자에게 맡깁니다. 외부 API·호스팅 제공자는 요청 처리, 보안 및 장애 대응을 위해 데이터를 처리하며, 제공자의 API 유형·프로젝트 설정·최신 약관에 따라 요청 로그나 제품 개선 관련 처리가 추가될 수 있습니다. 운영자는 각 기능에 필요한 입력만 전송하고, 외부 제공자의 별도 처리 여부와 보유기간은 아래 표 및 연결된 정책을 함께 안내합니다.':
    'The Operator entrusts the following processors with work necessary to provide the Service. External API and hosting providers process data for request handling, security, and incident response; request logging or product-improvement processing may also occur depending on the provider’s API type, project settings, and current terms. The Operator sends only the inputs needed for each feature and describes any separate processing and retention period in the table and linked policies below.',
  '수탁자': 'Processor',
  '위탁 업무': 'Outsourced work',
  '처리 항목': 'Categories of information',
  '처리 지역·조건': 'Processing region and conditions',
  'jsDelivr(Volentio JSD Limited) 및 CDN 하위 제공자': 'jsDelivr (Volentio JSD Limited) and CDN subprocessors',
  'Supabase, Inc.': 'Supabase, Inc.',
  '인증, 계정 관리, 데이터베이스 저장 및 동기화': 'Authentication, account management, database storage, and synchronization',
  '계정 정보, 메모·일정·수집함, 생성 결과, 설정': 'Account information, memos, schedules, saved links, generated results, and settings',
  '현재 프로젝트 리전: 대한민국 서울(ap-northeast-2)': 'Current project region: Seoul, Republic of Korea (ap-northeast-2)',
  'Subnota 백엔드 API 실행 및 사용자별 데이터 처리': 'Running the Subnota backend API and processing user data',
  '미국 중부(us-central1), 요청 시 TLS로 전송': 'Central United States (us-central1); transmitted over TLS upon request',
  'BAAI/bge-m3 기반 온라인 임베딩 생성': 'Online embedding generation using BAAI/bge-m3',
  '임베딩 대상 메모 청크, 수집함 요약 텍스트 및 요청 결과': 'Memo chunks and saved-link summary text submitted for embedding, and request results',
  'Hugging Face Inference의 요청 경로와 처리 지역·정책 적용': 'The request path, processing regions, and policies of Hugging Face Inference',
  '수집함 요약, 토픽 라벨 및 데일리 브리핑 생성': 'Generating saved-link summaries, topic labels, and daily briefings',
  '웹페이지 추출 텍스트, URL 메타데이터, 메모·일정·키워드 등 기능에 필요한 입력': 'Webpage-extracted text, URL metadata, and inputs needed by the feature, such as memos, schedules, and keywords',
  'Google API가 정하는 처리 지역. 현재 애플리케이션에서 별도 리전을 고정하지 않음': 'Processing regions determined by Google APIs. The application does not currently pin a separate region',
  '계정과 연결하지 않는 서비스 이용 통계': 'Service usage statistics not linked to accounts',
  '토큰이 설정된 배포에서의 플랫폼·환경 구분과 SDK 요청의 기술 정보. 메모 본문·이메일·계정 ID는 전송하지 않음': 'Platform and environment details and technical information from SDK requests in deployments with a token configured. Memo content, email addresses, and account IDs are not sent',
  '기본 호스트: 미국(us.i.posthog.com). 자동수집·페이지뷰·세션녹화·지속 저장 비활성화': 'Default host: United States (us.i.posthog.com). Automatic capture, pageviews, session recording, and persistent storage are disabled',
  'Subnota 웹사이트 호스팅·콘텐츠 전송 및 요청 보안': 'Subnota website hosting, content delivery, and request security',
  '웹사이트 요청의 IP 주소, 사용자 에이전트, 요청 시각 및 오류 로그': 'IP address, user agent, request time, and error logs from website requests',
  'Vercel의 글로벌 처리 인프라 및 제공자 로그 정책 적용. 앱 계정·메모 본문은 전송하지 않음': 'Vercel’s global processing infrastructure and provider log policy apply. App accounts and memo content are not sent',
  'Pretendard 글꼴 스타일시트·파일 전송': 'Delivery of Pretendard font stylesheets and files',
  '웹 요청의 IP 주소, 브라우저·사용자 에이전트, 참조 도메인, 요청 시각 및 요청 URL': 'IP address, browser and user agent, referrer domain, request time, and request URL from web requests',
  '글로벌 CDN 및 하위 제공자의 처리 지역·정책 적용': 'The processing regions and policies of the global CDN and its subprocessors',
  'Nanum Pen Script 글꼴 전송': 'Delivery of the Nanum Pen Script font',
  '글꼴 요청의 IP 주소, 브라우저·사용자 에이전트, 요청 URL 및 참조 URL': 'IP address, browser and user agent, request URL, and referrer URL from font requests',
  'Google Fonts 서버 및 Google의 처리 지역·정책 적용': 'Google Fonts servers and Google’s processing regions and policies',
  'SF Pro 및 SF Pro KR 글꼴 전송': 'Delivery of SF Pro and SF Pro KR fonts',
  'Apple의 글로벌 처리 인프라 및 제공자 정책 적용': 'Apple’s global processing infrastructure and provider policy',
  '수탁자 또는 위탁 업무가 변경되면 변경 내용을 이 방침에 반영합니다. 각 제공자의 최신 개인정보 처리방침은':
    'If a processor or outsourced work changes, the change will be reflected in this policy. The current privacy policies of the providers are available from ',
  '에서 확인할 수 있습니다. 웹 글꼴 제공자의 정책은': '. The policies of the web-font providers are available from ',
  '및': ' and ',
  ',': ', ',
  '에서 확인할 수 있습니다.': '.',
  '개인정보 안내': 'privacy notice',
  'Google Cloud 개인정보 안내': 'Google Cloud privacy notice',
  'Vercel 개인정보 처리방침': 'Vercel privacy policy',
  'jsDelivr 정책': 'jsDelivr policy',
  'Google Fonts 정책': 'Google Fonts policy',
  '8. 개인정보의 국외 수집 및 이전': '8. Collection and Transfer of Personal Information Overseas',
  '서비스의 백엔드, 온라인 AI·임베딩 기능, 웹사이트 호스팅 및 익명 통계는 국외 사업자 또는 국외 처리 인프라를 사용하므로 다음과 같이 개인정보가 국외로 이전될 수 있습니다. 이전의 법적 근거는 서비스 제공을 위한 개인정보 보호법 제28조의8제1항제3호(계약 이행을 위한 처리위탁)입니다.':
    'The Service backend, online AI and embedding features, website hosting, and anonymous statistics use overseas businesses or processing infrastructure, so personal information may be transferred overseas as described below. The legal basis for the transfer is Article 28-8(1)3 of the Personal Information Protection Act (outsourcing processing to perform a contract).',
  '이전받는 자·국가': 'Recipient and country',
  '이전 항목': 'Transferred information',
  '시기·방법': 'Timing and method',
  '목적·보유기간': 'Purpose and retention period',
  '미국, 연락처:': 'United States; contact:',
  '인증 토큰, 사용자 ID, 메모·일정·수집함, 생성 결과, 운영 로그': 'Authentication tokens, user IDs, memos, schedules, saved links, generated results, and operational logs',
  '백엔드 API 이용 시 TLS 암호화 전송': 'Transferred with TLS encryption when using the backend API',
  '백엔드 기능 제공 및 보안·장애 대응. 계정 삭제 또는 목적 달성 시까지, 운영 로그는 제공자 설정 기간': 'Backend functionality, security, and incident response. Until account deletion or the purpose is achieved; operational logs are retained for the period configured by the provider',
  '미국 및 Google API가 정하는 처리 국가, 연락처:': 'United States and processing countries determined by Google APIs; contact:',
  '요약·분류·브리핑에 필요한 웹페이지 텍스트, URL 메타데이터, 메모·일정·키워드': 'Webpage text, URL metadata, memos, schedules, and keywords needed for summaries, categorization, and briefings',
  '해당 AI 기능을 실행할 때 TLS 암호화 API 요청으로 전송': 'Transferred in a TLS-encrypted API request when the relevant AI feature runs',
  'AI 결과 생성. Subnota가 별도 원문 요청 로그를 보관하지 않으며, Google API 프로젝트와 이용 유형에 따른 제공자 보관정책 적용': 'Generating AI results. Subnota does not retain separate logs of original requests; the provider’s retention policy for the Google API project and usage type applies',
  '미국 등 제공자의 처리 국가, 연락처:': 'The provider’s processing countries, including the United States; contact:',
  '온라인 임베딩 대상 메모 청크·수집함 요약과 임베딩 응답': 'Memo chunks and saved-link summaries submitted for online embedding, and embedding responses',
  '온라인 검색·색인 기능 실행 시 TLS 암호화 API 요청으로 전송': 'Transferred in a TLS-encrypted API request when online search or indexing runs',
  'BAAI/bge-m3 기반 임베딩 생성. Hugging Face Inference의 요청 로그·보관 정책에 따른 기간': 'Generating embeddings using BAAI/bge-m3. Retained for the period specified by Hugging Face Inference request-log and retention policies',
  '미국(us.i.posthog.com), 연락처:': 'United States (us.i.posthog.com); contact:',
  '계정과 연결하지 않는 플랫폼·환경 구분, 이용 통계 및 SDK 요청의 기술 정보': 'Platform and environment details, usage statistics, and technical information from SDK requests that are not linked to accounts',
  '분석 토큰이 설정된 웹·데스크톱 배포에서 SDK가 HTTPS로 전송할 수 있음': 'The SDK may transmit over HTTPS from web and desktop deployments with an analytics token configured',
  '서비스 사용성 분석. 지속 식별자와 메모·계정 정보는 사용하지 않으며, 제공자 프로젝트 보관 설정 적용': 'Analyzing Service usability. Persistent identifiers, memo content, and account information are not used; the provider project’s retention settings apply',
  '미국 및 Vercel의 처리 국가, 연락처:': 'United States and Vercel’s processing countries; contact:',
  '웹사이트 접속 IP, 사용자 에이전트, 요청 시각 및 오류 로그': 'Website access IP address, user agent, request time, and error logs',
  '웹사이트 접속 시 글로벌 전송망을 통해 자동 전송': 'Automatically transmitted over the global delivery network when the website is accessed',
  '웹사이트 제공과 보안. Vercel의 로그·보안 보관정책에 따른 기간': 'Website delivery and security. Retained for the period specified by Vercel’s log and security retention policies',
  '미국 등 CDN 제공자의 처리 국가, 연락처:': 'The processing countries of CDN providers, including the United States; contact:',
  '웹 글꼴 요청의 IP 주소, 브라우저·사용자 에이전트, 참조 도메인, 요청 시각 및 요청 URL': 'IP address, browser and user agent, referrer domain, request time, and request URL from web-font requests',
  '웹페이지에서 Pretendard 글꼴을 요청할 때 글로벌 CDN을 통해 전송': 'Transferred through a global CDN when Pretendard is requested by the webpage',
  '글꼴 전송 및 CDN 보안·장애 대응. jsDelivr 및 하위 제공자의 정책에 따른 기간': 'Font delivery and CDN security and incident response. Retained for the period specified by jsDelivr and its subprocessors',
  '미국 등 Google의 처리 국가, 연락처:': 'Google’s processing countries, including the United States; contact:',
  '웹페이지에서 Nanum Pen Script 글꼴을 요청할 때 HTTPS로 전송': 'Transferred over HTTPS when Nanum Pen Script is requested by the webpage',
  '글꼴 전송 및 보안. Google Fonts 및 Google의 정책에 따른 기간': 'Font delivery and security. Retained for the period specified by Google Fonts and Google policies',
  '미국 등 Apple의 처리 국가, 연락처:': 'Apple’s processing countries, including the United States; contact:',
  'Apple 개인정보 처리방침': 'Apple privacy policy',
  '웹페이지에서 SF Pro 글꼴을 요청할 때 HTTPS로 전송': 'Transferred over HTTPS when SF Pro is requested by the webpage',
  '글꼴 전송 및 보안. Apple의 정책에 따른 기간': 'Font delivery and security. Retained for the period specified by Apple’s policies',
  '국외 이전은 계정 동기화, 온라인 AI·임베딩, 웹사이트 또는 통계 기능을 제공하기 위해 필요한 처리입니다. 국외 이전을 원하지 않으면 회원가입·동기화 및 해당 온라인 기능을 이용하지 않을 수 있으며, 이미 가입한 이용자는 앱의 계정 삭제 기능 또는':
    'Overseas transfers are necessary to provide account synchronization, online AI and embedding, website, or statistics features. If you do not want an overseas transfer, you may choose not to sign up, synchronize, or use the relevant online features. Existing users may request account deletion through the app’s account deletion function or ',
  '을 통해 계정 삭제를 요청할 수 있습니다. 국외 이전을 거부하면 서버 동기화와 일부 온라인 기능을 이용할 수 없습니다.':
    '. If you refuse an overseas transfer, server synchronization and some online features will not be available.',
  '9. 추가적인 이용·제공': '9. Additional Use and Provision',
  '현재 당초 수집 목적과 별도로 지속적으로 개인정보를 추가 이용하거나 제공하는 처리는 하지 않습니다. 향후 서비스 개선·연구·모델 학습 등 추가 목적의 처리를 도입하면 관련성, 예측 가능성, 이용자 이익 침해 여부 및 가명처리·암호화 등 안전조치를 검토하고 이 방침에 판단 기준과 상세 내용을 공개합니다.':
    'We do not currently carry out ongoing additional use or provision of personal information beyond the original collection purposes. If we introduce additional purposes such as Service improvement, research, or model training, we will assess relevance, predictability, potential impact on user interests, and safeguards such as pseudonymization and encryption, then disclose the criteria and details in this policy.',
  '10. 생성형 AI 및 임베딩 처리': '10. Generative AI and Embedding Processing',
  'AI 기능의 의도된 용례는 이용자가 저장한 메모·일정·웹페이지 정보를 요약, 분류, 임베딩하고 그 결과를 검색·연결·브리핑 기능에 활용하는 것입니다. AI 기능은 이용자의 요청과 서비스 기능 제공을 위한 보조 수단이며, 의료·법률·재무 판단, 채용, 자격 심사 또는 이용자의 권리·의무에 관한 결정을 자동으로 내리는 데 사용하지 않습니다.':
    'The intended use of the AI features is to summarize, categorize, and embed memos, schedules, and webpages saved by users, and to use the results for search, connections, and briefings. AI features assist with user requests and Service functionality; they are not used to make automated medical, legal, financial, hiring, eligibility, or rights-and-obligations decisions.',
  '입력: 메모 청크, 일정 정보, 사용자가 저장한 URL과 웹페이지 메타데이터·추출 텍스트, 서비스가 생성한 키워드 등 기능에 필요한 정보':
    'Input: Information needed by the feature, such as memo chunks, schedule information, user-saved URLs, webpage metadata and extracted text, and keywords generated by the Service',
  '결과: 요약, 키워드, 토픽 라벨, 임베딩 벡터, 유사도·연결 결과 및 데일리 브리핑':
    'Results: Summaries, keywords, topic labels, embedding vectors, similarity and connection results, and daily briefings',
  '보관: 서비스에 저장되는 결과는 계정이 유지되는 동안 보관하고 계정 삭제 시 삭제합니다. 외부 API의 일시적 요청 로그·캐시는 각 제공자의 정책에 따릅니다.':
    'Retention: Results stored in the Service are retained while the account is active and deleted when the account is deleted. Temporary request logs and caches of external APIs are subject to each provider’s policy.',
  '학습: 운영자는 이용자 입력과 생성 결과를 자체 AI 모델 학습에 사용하지 않습니다. 외부 제공자의 제품 개선·학습 여부는 제공자의 API 유형, 결제 상태, 프로젝트 설정 및 최신 약관에 따라 달라질 수 있으므로 민감하거나 비밀인 정보를 입력하지 마세요.':
    'Training: The Operator does not use user inputs or generated results to train its own AI models. Whether an external provider uses data for product improvement or training may depend on its API type, payment status, project settings, and current terms, so do not enter sensitive or confidential information.',
  '외부 AI 학습·제품 개선 거부: 현재 Subnota에는 외부 AI 제공자의 학습·제품 개선을 별도로 선택하거나 거부하는 앱 설정이 없습니다. 이용자는 온라인 AI 기능을 사용하지 않음으로써 해당 요청의 외부 전송을 피할 수 있고, 데스크톱의 로컬 임베딩은 기기에서 처리됩니다. 외부 제공자가 별도 거부 설정을 제공하는 경우에는 해당 제공자의 설정과 정책을 따라야 합니다.':
    'Refusing external AI training or product improvement: Subnota currently has no app setting to separately opt in to or refuse an external AI provider’s training or product improvement. Users can avoid external transmission for a request by not using online AI features; desktop local embeddings are processed on the device. If an external provider offers a separate opt-out setting, follow that provider’s settings and policy.',
  '로컬 임베딩: 데스크톱 앱의 Xenova/bge-m3 모델은 기기에서 실행되며, 해당 임베딩 계산을 위해 메모가 외부로 전송되지 않습니다. 백엔드 온라인 임베딩은 Hugging Face Inference를 통해 BAAI/bge-m3 모델로 처리합니다.':
    'Local embeddings: The Xenova/bge-m3 model in the desktop app runs on the device, and memos are not sent externally to calculate those embeddings. Backend online embeddings are processed with the BAAI/bge-m3 model through Hugging Face Inference.',
  '주민등록번호, 건강정보, 금융정보, 비밀번호, 타인의 비공개 정보 등 민감하거나 중요한 정보는 자유 입력 영역에 넣지 않는 것을 권장합니다. 서비스는 이용자가 입력한 내용을 완벽하게 탐지하거나 안전성을 보장하지 않습니다.':
    'We recommend that you do not enter sensitive or important information, such as national identification numbers, health information, financial information, passwords, or another person’s private information, into free-entry fields. The Service cannot perfectly detect user input or guarantee its safety.',
  '11. 가명정보 처리': '11. Processing of Pseudonymized Information',
  '운영자는 현재 통계·연구·모델 학습을 위한 개인정보 보호법 제28조의2 및 제28조의3의 가명정보 처리 업무를 하지 않습니다. 서비스에서 생성되는 임베딩, 요약 및 연결 결과는 기능 제공을 위해 사용자 계정과 연결된 서비스 결과로 처리하며, 가명정보로 별도 이용하지 않습니다.':
    'The Operator does not currently process pseudonymized information under Articles 28-2 and 28-3 of the Personal Information Protection Act for statistics, research, or model training. Embeddings, summaries, and connection results generated by the Service are processed as Service results linked to user accounts to provide features and are not separately used as pseudonymized information.',
  '12. 민감정보의 공개 가능성': '12. Possibility of Disclosing Sensitive Information',
  'Subnota는 이용자 콘텐츠를 다른 이용자에게 공개하는 게시판·공개 프로필·공유 피드 기능을 제공하지 않습니다. 따라서 서비스가 민감정보를 공개하도록 설정하는 기능은 없습니다. 다만 이용자가 자신의 기기나 계정 접근권한을 다른 사람과 공유하면 그 사람이 콘텐츠를 볼 수 있으므로 인증 정보와 기기를 안전하게 관리해야 합니다.':
    'Subnota does not provide a bulletin board, public profile, or shared feed that exposes user content to other users. The Service therefore has no setting that makes sensitive information public. However, if a user shares access to their device or account with another person, that person may see the content; authentication information and devices must be managed securely.',
  '13. 개인정보 자동 수집 장치 및 거부 방법': '13. Automatic Collection Devices and How to Refuse Them',
  'Subnota의 공개 웹사이트는 자체적으로 광고 쿠키나 로그인 쿠키를 설정하지 않습니다. PostHog 토큰이 설정된 경우에만 분석 SDK가 로드될 수 있으며, 현재 설정은 자동수집, 페이지뷰, 페이지 이탈, 세션 녹화 및 지속적인 브라우저·기기 식별자 저장을 사용하지 않습니다. IP 주소를 이벤트 속성으로 수집하지 않도록 설정했으며, SDK는 계정 ID, 이메일 및 메모 본문을 전송하지 않도록 구성되어 있습니다. 다만 네트워크 요청 자체에는 서비스 제공자에게 전달되는 기술 정보가 포함될 수 있습니다.':
    'Subnota’s public website does not set advertising or login cookies by itself. The analytics SDK may load only when a PostHog token is configured. The current configuration does not use automatic capture, pageviews, page exits, session recording, or persistent browser and device identifiers. It is configured not to collect IP addresses as event properties, and the SDK is configured not to send account IDs, email addresses, or memo content. Network requests themselves may nevertheless contain technical information delivered to service providers.',
  '웹사이트는 글꼴 표시를 위해 jsDelivr, Google Fonts 및 Apple Web Fonts에 브라우저 요청을 보낼 수 있습니다. 이 요청에는 글꼴 제공에 필요한 IP 주소, 브라우저 정보, 요청 URL 또는 참조 URL이 포함될 수 있으며, 자세한 처리 내용은 제7항과 제8항에 안내합니다.':
    'The website may send browser requests to jsDelivr, Google Fonts, and Apple Web Fonts to display fonts. These requests may include the IP address, browser information, request URL, or referrer URL needed to provide the font; Sections 7 and 8 describe the processing in more detail.',
  '이용자는 웹브라우저의 사이트 데이터·스크립트·제3자 요청 차단 설정 또는 광고·추적 차단 기능으로 PostHog 요청을 차단할 수 있습니다. 데스크톱 앱은 네트워크 차단 기능을 사용하면 통계 전송만 차단되며, 메모·일정의 로컬 이용은 계속할 수 있습니다. 통계 기능을 식별 가능한 분석이나 맞춤형 광고로 변경할 경우 사전에 이 방침과 거부 방법을 갱신합니다.':
    'Users can block PostHog requests through browser settings that block site data, scripts, or third-party requests, or through ad and tracking blockers. In the desktop app, blocking the network blocks only statistics transmission; local use of memos and schedules can continue. If the statistics feature changes to identifiable analytics or personalized advertising, this policy and the refusal methods will be updated in advance.',
  '14. 제3자 웹·앱의 행태정보 수집': '14. Behavioral Information Collection by Third-Party Websites and Apps',
  'Subnota는 제3자가 운영하는 웹사이트나 앱에 추적 픽셀·광고 SDK를 설치하지 않으며, 제3자의 행태정보를 수집하도록 허용하지 않습니다.':
    'Subnota does not install tracking pixels or advertising SDKs in websites or apps operated by third parties and does not permit the collection of third-party behavioral information.',
  '15. 권리·의무 및 행사 방법': '15. Rights, Obligations, and How to Exercise Them',
  '이용자는 자신의 개인정보에 대해 열람, 정정, 삭제, 처리정지 및 동의 철회를 요구할 수 있습니다. 현재 동의에 기반한 선택 처리 항목은 없지만, 향후 동의 항목이 추가되면 같은 연락처로 철회를 요청할 수 있습니다.':
    'Users may request access to, correction of, deletion of, or suspension of processing of their personal information, and may withdraw consent. There are currently no optional categories processed based on consent; if consent-based categories are added, withdrawal may be requested through the same contact address.',
  '계정 삭제: 데스크톱 앱 설정 → 계정 → 계정 및 데이터 삭제 또는 모바일 앱 노트 화면의 옵션 메뉴 → 계정 및 데이터 삭제에서 요청합니다. 앱을 사용할 수 없으면':
    'Account deletion: Request it from Desktop app Settings → Account → Delete account and data, or from the mobile app’s Note screen Options menu → Delete account and data. If you cannot use the app, use the email method in',
  '계정 삭제 안내': 'the account deletion guide',
  '의 이메일 방법을 이용합니다.': '.',
  '그 밖의 열람·정정·삭제·처리정지: 요청할 개인정보의 범위와 사유를':
    'Other access, correction, deletion, or suspension requests: Send the scope and reason for the request to ',
  '으로 보내 주세요.': '.',
  '본인 확인: 운영자는 계정 이메일, 인증 상태 또는 추가 자료로 본인 여부를 확인할 수 있습니다. 대리인은 위임 관계를 확인할 수 있는 자료를 제출해야 합니다.':
    'Identity verification: The Operator may verify identity using the account email, authentication status, or additional materials. An agent must submit materials that verify the agency relationship.',
  '처리 기간: 운영자는 권리 행사 요청을 접수한 날부터 10일 이내에 조치 결과를 회신하도록 노력하며, 법령에 따른 제한이나 연장이 있는 경우 그 사유를 안내합니다.':
    'Processing period: The Operator will endeavor to reply with the result within 10 days of receiving a rights request and will explain the reason for any restriction or extension required by law.',
  '현재 Subnota는 개인정보 전송요구권의 대상이 되는 정보전송자로 지정되어 있지 않아 별도의 전송요구 기능을 제공하지 않습니다. 다른 법령에서 보존을 요구하는 정보, 타인의 권리를 침해할 우려가 있는 정보 또는 법령상 제한되는 정보는 삭제·처리정지 요청이 제한될 수 있습니다.':
    'Subnota is not currently designated as an information transmitter subject to the right to request transmission of personal information, so it does not provide a separate transmission-request feature. Requests to delete or suspend processing may be restricted for information that another law requires us to retain, information that may infringe another person’s rights, or information restricted by law.',
  '16. 자동화된 결정': '16. Automated Decisions',
  'Subnota는 개인정보를 완전히 자동으로 처리하여 이용자의 서비스 이용 자격, 가격, 혜택, 채용, 신용, 법적 지위 또는 그 밖의 권리·의무에 영향을 주는 자동화된 결정을 하지 않습니다. 요약·분류·토픽·추천 결과는 서비스 기능을 보조하는 생성 결과이며, 이용자에게 불이익을 주는 결정의 근거로 사용하지 않습니다.':
    'Subnota does not make automated decisions that fully automatically process personal information and affect a user’s eligibility to use the Service, price, benefits, hiring, credit, legal status, or other rights or obligations. Summaries, categories, topics, and recommendations are generated results that assist Service features and are not used as the basis for decisions that disadvantage users.',
  '17. 안전성 확보조치': '17. Safeguards',
  '전송 구간 TLS 암호화': 'TLS encryption in transit',
  'Supabase 인증 토큰 기반 접근 및 사용자별 데이터 접근 제어': 'Supabase authentication-token access and per-user data access controls',
  '백엔드 서비스에만 비밀키를 보관하고 클라이언트에 service-role 키를 포함하지 않는 조치': 'Keeping secret keys only in backend services and not including service-role keys in clients',
  '운영에 필요한 최소 권한, RLS 및 백엔드 사용자 소유권 검증': 'Least privilege needed for operations, RLS, and backend verification of user ownership',
  '계정 삭제 시 서버 데이터와 인증 계정을 함께 삭제하는 절차': 'A procedure that deletes server data and the authentication account together when an account is deleted',
  '기기 내 데이터베이스와 로컬 모델 캐시의 운영체제 저장소 사용': 'Using operating-system storage for the on-device database and local model cache',
  '운영자는 접근권한을 업무상 필요한 범위로 제한하고, 보안·장애 대응 로그에 메모 본문을 의도적으로 기록하지 않습니다. 다만 인터넷, 운영체제, 외부 서비스 및 기기 저장 환경의 특성상 완전한 보안을 보장할 수는 없습니다.':
    'The Operator limits access rights to what is necessary for work and does not intentionally record memo content in security or incident-response logs. However, complete security cannot be guaranteed given the nature of the internet, operating systems, external services, and device storage environments.',
  '18. 권익침해 구제 방법': '18. Remedies for Infringement of Rights and Interests',
  '운영자에게 문의하여 해결되지 않거나 외부 구제가 필요한 경우 다음 기관에 상담 또는 분쟁조정을 신청할 수 있습니다.':
    'If an issue cannot be resolved by contacting the Operator or requires an external remedy, users may seek consultation or dispute mediation from the following organizations.',
  '개인정보침해 신고센터': 'Personal Information Infringement Report Center',
  '국번 없이 118': '118 (no area code)',
  '- 국번 없이 118': '- 118 (no area code)',
  '개인정보분쟁조정위원회': 'Personal Information Dispute Mediation Committee',
  '개인정보보호위원회': 'Personal Information Protection Commission',
  '개인정보 관련 신고·상담': 'Privacy reports and consultations',
  '- 개인정보 관련 신고·상담': '- privacy reports and consultations',
  '개인정보보호위원회 - 개인정보 관련 신고·상담': 'Personal Information Protection Commission - privacy reports and consultations',
  '19. 국내대리인': '19. Domestic Representative',
  '운영자는 국내에 거주하는 개인 운영자로서 별도의 국내대리인을 지정하지 않습니다. 국내대리인 지정 의무가 발생하는 사업자 구조로 변경되면 관련 정보를 이 방침에 추가합니다.':
    'The Operator is an individual operator residing in Korea and does not appoint a separate domestic representative. If the business structure changes so that appointing a domestic representative is required, the relevant information will be added to this policy.',
  '20. 영상정보처리기기': '20. Video Information Processing Devices',
  '운영자는 고정형 영상정보처리기기나 이동형 영상정보처리기기를 설치·운영하지 않으며, 카메라 영상정보를 서비스 제공을 위해 수집·이용하지 않습니다.':
    'The Operator does not install or operate fixed or mobile video information processing devices and does not collect or use camera video information to provide the Service.',
  '21. 개인정보 처리방침의 변경': '21. Changes to this Privacy Policy',
  '이 방침은 2026년 8월 15일부터 적용됩니다. 향후 처리하는 개인정보의 항목·목적·보유기간, 수탁자, 국외 이전 국가 또는 이용자의 권리에 중요한 변경이 있으면 변경 내용과 시행일을 이 페이지에 게시하고, 필요한 경우 로그인 화면·앱 설정·공지 등 이용자가 쉽게 확인할 수 있는 방법으로 안내합니다.':
    'This policy applies from August 15, 2026. If there is a material change to the categories, purposes, or retention periods of personal information processed, processors, countries of overseas transfer, or user rights, we will post the changes and effective date on this page and, where necessary, provide notice in a way users can easily see, such as the login screen, app settings, or an announcement.',
  '이전 버전이 생기면 각 버전의 적용기간과 변경 내용을 함께 공개하여 확인할 수 있도록 하겠습니다. 최신 내용은 언제든지 이 페이지에서 확인할 수 있습니다.':
    'If a previous version is created, we will publish its effective period and changes so they can be reviewed. The latest version is always available on this page.',
});

export const termsTranslations = defineTranslations({
  '이 약관은 오성훈(이하 “운영자”)이 제공하는 Subnota(이하 “서비스”)의 이용 조건과 절차를 정합니다. 서비스 이용자는 이 약관과':
    'These Terms set out the conditions and procedures for using Subnota (the “Service”) provided by Oh Seonghun (the “Operator”). Service users must review these Terms and ',
  '개인정보 처리방침': 'Privacy Policy',
  '을 확인해야 합니다.': '.',
  '제1조 목적': 'Article 1. Purpose',
  '이 약관은 Subnota가 제공하는 메모, 캘린더, 수집함, 검색, 브리핑, 네트워크, AI 및 관련 앱·웹 기능의 이용 조건과 절차, 운영자와 이용자의 권리·의무 및 책임사항을 정합니다.':
    'These Terms set out the conditions and procedures for using the memos, calendar, saved links, search, briefings, network, AI, and related app and web features provided by Subnota, as well as the rights, obligations, and responsibilities of the Operator and users.',
  '제2조 서비스의 성격과 제공 범위': 'Article 2. Nature and Scope of the Service',
  'Subnota는 메모와 일정, 저장한 웹페이지 및 서비스 생성 결과를 기기에 저장하고, 이용자가 선택한 경우 서버와 동기화하는 개인 지식관리 서비스입니다.':
    'Subnota is a personal knowledge-management service that stores memos, schedules, saved webpages, and Service-generated results on a device and synchronizes them with the server when the user chooses to do so.',
  '현재 서비스는 무료로 제공되며, 결제·유료 플랜·환불·청약철회 및 디지털 콘텐츠 거래 기능은 제공하지 않습니다.':
    'The Service is currently provided free of charge and does not offer payment, paid plans, refunds, withdrawal rights, or digital-content transactions.',
  '결제 또는 유료 기능을 출시할 때에는 가격, 결제, 해지, 환불 및 청약철회에 관한 내용을 별도로 안내하고 필요한 약관을 추가합니다.':
    'If payment or paid features are introduced, we will separately explain pricing, payment, cancellation, refunds, and withdrawal rights and add any necessary terms.',
  '서비스의 일부 기능은 인터넷 연결과 Supabase, Google Cloud, Hugging Face, Google Gemini 등 외부 서비스에 의존할 수 있습니다. 외부 서비스의 장애나 정책 변경으로 일부 기능이 제한될 수 있습니다.':
    'Some Service features may depend on an internet connection and external services such as Supabase, Google Cloud, Hugging Face, and Google Gemini. Some features may be limited by an outage or policy change at an external service.',
  '제3조 이용계약과 약관의 확인': 'Article 3. Service Agreement and Review of the Terms',
  '이용자가 가입 또는 로그인 화면에서 필요한 정보를 입력하고 계속하기를 선택하면, 이 약관에 동의하고 서비스 이용계약을 신청한 것으로 봅니다.':
    'When a user enters the required information on the sign-up or login screen and chooses to continue, the user is deemed to have agreed to these Terms and applied to enter into a Service agreement.',
  '계속하면 서비스 이용약관에 동의하며, 개인정보 처리방침에 따라 개인정보가 처리됩니다. 개인정보 처리방침은 처리 현황을 알리는 문서이며, 그 내용은':
    'By continuing, you agree to these Terms, and personal information will be processed according to the Privacy Policy. The Privacy Policy describes processing practices, and its contents are available in the ',
  '운영자는 계정 생성이 완료되거나 이용자가 서비스를 실제로 이용하는 경우 이용 신청을 승낙합니다. 기술적·보안상 사유 또는 법령 위반 우려가 있는 경우 승낙을 보류하거나 제한할 수 있습니다.':
    'The Operator accepts the application when account creation is complete or when the user actually uses the Service. Acceptance may be deferred or limited for technical or security reasons or where there is a concern about violating the law.',
  '제4조 계정과 인증': 'Article 4. Accounts and Authentication',
  '이용자는 본인의 이메일 또는 Google 등 제공된 인증수단을 사용하여 계정을 만들어야 하며, 정확한 정보를 입력해야 합니다.':
    'Users must create an account using their own email or an available authentication method such as Google and must provide accurate information.',
  'Google 로그인을 이용하는 경우 Google의 인증 결과로 전달되는 이메일, 제공자 및 제공자 사용자 식별자가 Subnota 계정과 연결될 수 있습니다.':
    'When Google sign-in is used, the email, provider, and provider user identifier returned by Google authentication may be linked to the Subnota account.',
  '이용자는 인증 정보와 기기를 안전하게 관리해야 하며, 제3자에게 계정을 양도하거나 공유해서는 안 됩니다. 계정 도용이나 비정상 이용을 알게 되면 즉시 운영자에게 알려야 합니다.':
    'Users must keep their authentication information and devices secure and must not transfer or share their account with a third party. If they become aware of account theft or abnormal use, they must notify the Operator immediately.',
  '이용자는 언제든지 앱의 설정 또는 계정 삭제 안내에 따라 계정과 데이터를 삭제할 수 있습니다.':
    'Users may delete their account and data at any time through the app settings or the account deletion instructions.',
  '서비스는 만 14세 미만 아동을 주 이용자로 하지 않습니다. 만 14세 미만 이용자는 법정대리인의 도움 없이 가입하거나 이용해서는 안 됩니다. Google Gemini API를 사용하는 온라인 AI 기능은 제공자의 연령·이용 조건도 적용됩니다.':
    'The Service is not directed primarily to children under 14. Users under 14 must not sign up for or use the Service without a legal guardian’s assistance. The provider’s age and usage requirements also apply to online AI features that use the Google Gemini API.',
  '제5조 이용자의 콘텐츠와 처리 권한': 'Article 5. User Content and Processing Rights',
  '이용자가 작성하거나 저장한 메모, 일정, 링크 및 기타 자료에 대한 권리는 원칙적으로 이용자 또는 정당한 권리자에게 있습니다.':
    'Rights to memos, schedules, links, and other materials created or saved by a user generally belong to the user or the rightful owner.',
  '이용자는 운영자가 서비스를 제공하는 데 필요한 범위에서 콘텐츠를 저장, 동기화, 검색, 색인, 형식 변환, 요약, 분류, 임베딩 및 연결할 수 있도록 비독점적이고 서비스 제공 기간 동안의 처리 권한을 부여합니다. 이 권한은 콘텐츠의 소유권을 운영자에게 이전하는 것이 아닙니다.':
    'The user grants the Operator a non-exclusive right, for the period of Service provision and to the extent necessary to provide the Service, to store, synchronize, search, index, transform, summarize, categorize, embed, and connect the content. This right does not transfer ownership of the content to the Operator.',
  '위 처리는 서비스 기능 제공을 위해 Supabase, Google Cloud, Hugging Face 및 Google Gemini 등 수탁자를 통해 수행될 수 있습니다. 자세한 처리 항목과 이전 내용은':
    'This processing may be carried out through processors such as Supabase, Google Cloud, Hugging Face, and Google Gemini to provide Service features. Detailed categories and transfers are described in the ',
  '을 따릅니다.': '.',
  '계정 삭제 또는 서비스 이용 종료 후에는 서비스 제공을 위한 처리 권한이 종료됩니다. 다만 법령상 보존 또는 백업·보안 로그의 잔여 보관이 필요한 경우에는 해당 범위와 기간 동안만 처리될 수 있습니다.':
    'The processing right for providing the Service ends after account deletion or termination of Service use. However, processing may continue only to the extent and for the period necessary for legally required retention or residual retention in backups and security logs.',
  '이용자는 자신이 입력하거나 저장하는 콘텐츠에 필요한 권리와 동의를 가지고 있어야 하며, 타인의 개인정보, 영업비밀 또는 저작물을 권리 없이 입력하거나 저장해서는 안 됩니다.':
    'Users must have the rights and consents necessary for content they enter or save and must not enter or save another person’s personal information, trade secrets, or copyrighted works without authorization.',
  '제6조 AI 및 자동 생성 결과': 'Article 6. AI and Automatically Generated Results',
  '서비스는 메모·일정·저장한 웹페이지를 요약, 분류, 임베딩, 연결하거나 브리핑을 생성할 수 있습니다. 일부 온라인 기능은 외부 AI 처리 서비스로 입력 내용을 전송할 수 있습니다.':
    'The Service may summarize, categorize, embed, and connect memos, schedules, and saved webpages or generate briefings. Some online features may transmit input to an external AI processing service.',
  'AI가 생성한 요약·분류·추천·브리핑은 입력 데이터와 모델의 한계로 부정확할 수 있으며, 중요한 판단이나 법률·의료·재무 결정을 대신하는 자료가 아닙니다.':
    'AI-generated summaries, categories, recommendations, and briefings may be inaccurate because of limitations in the input data and models and are not a substitute for important judgments or legal, medical, or financial decisions.',
  '운영자는 이용자의 콘텐츠를 자체 AI 모델 학습 데이터로 사용하지 않습니다. 외부 AI 제공자의 API 유형, 결제 상태, 보관 및 제품 개선 조건은 제공자의 최신 약관과 프로젝트 설정에 따라 달라질 수 있습니다.':
    'The Operator does not use user content as training data for its own AI models. An external AI provider’s API type, payment status, retention, and product-improvement conditions may vary according to its current terms and project settings.',
  '주민등록번호, 건강정보, 금융정보, 비밀번호 또는 타인의 민감한 정보를 자유 입력 영역에 넣지 않는 것을 권장합니다. 이용자가 입력한 정보에 대해 서비스가 완전한 안전성이나 민감정보 자동 탐지를 보장하지는 않습니다.':
    'We recommend that users do not enter national identification numbers, health information, financial information, passwords, or another person’s sensitive information into free-entry fields. The Service does not guarantee complete safety or automatic detection of sensitive information in user input.',
  '제7조 금지행위': 'Article 7. Prohibited Conduct',
  '이용자는 다음 행위를 해서는 안 됩니다.': 'Users must not engage in the following conduct.',
  '타인의 계정이나 인증 정보를 무단으로 사용하는 행위': 'Using another person’s account or authentication information without authorization',
  '서비스의 정상적인 운영을 방해하거나 보안 취약점을 악용하는 행위': 'Interfering with normal Service operation or exploiting a security vulnerability',
  '불법, 명예훼손, 사기, 악성코드 또는 타인의 권리를 침해하는 콘텐츠를 전송하는 행위': 'Sending content that is illegal, defamatory, fraudulent, malicious, or infringes another person’s rights',
  '서비스를 역설계하거나 제공량 제한·접근 제어를 우회하는 행위': 'Reverse engineering the Service or bypassing usage limits or access controls',
  '서비스를 이용하여 타인을 감시, 괴롭히거나 법령을 위반하는 행위': 'Using the Service to surveil or harass another person or violate the law',
  '자동화된 요청, 스크래핑 또는 과도한 요청으로 서비스나 외부 제공자에 부담을 주는 행위': 'Burdening the Service or an external provider with automated requests, scraping, or excessive requests',
  '제8조 지식재산권과 오픈소스': 'Article 8. Intellectual Property and Open Source',
  'Subnota의 상표, 소프트웨어, 화면 구성, 문서 및 서비스에 포함된 자료의 권리는 운영자 또는 정당한 권리자에게 있습니다.':
    'Rights to Subnota’s trademarks, software, interface, documentation, and materials included in the Service belong to the Operator or the rightful owner.',
  '서비스에는 오픈소스 소프트웨어와 모델이 포함될 수 있으며, 각 구성요소는 해당 라이선스의 조건을 따릅니다. 데스크톱 앱의 로컬 임베딩 모델과 백엔드 임베딩 모델의 라이선스 및 고지는 앱 설정의 오픈소스 라이선스 안내와 저장소의':
    'The Service may include open-source software and models, and each component is subject to its applicable license. Licenses and notices for the desktop app’s local embedding model and backend embedding model are available in the app settings’ open-source license notice and in',
  '에서 확인할 수 있습니다.': '.',
  '이용자는 서비스 또는 오픈소스 구성요소의 저작권·라이선스 표시를 삭제하거나 변경해서는 안 됩니다.':
    'Users must not remove or change copyright or license notices for the Service or its open-source components.',
  '제9조 서비스의 변경·중단': 'Article 9. Changes to and Suspension of the Service',
  '운영자는 기능 개선, 보안, 외부 서비스 변경, 장애, 유지보수 또는 운영상 필요에 따라 서비스의 전부 또는 일부를 변경하거나 일시 중단할 수 있습니다. 중대한 변경이나 장기 중단이 예상되는 경우 가능한 방법으로 안내합니다. 불가피한 긴급 보안 조치나 외부 서비스 장애의 경우 사후 안내할 수 있습니다.':
    'The Operator may change or temporarily suspend all or part of the Service for feature improvements, security, changes to external services, incidents, maintenance, or operational needs. If a material change or extended suspension is expected, notice will be provided through available means. Unavoidable emergency security measures or external-service outages may be announced afterward.',
  '제10조 계정 해지와 콘텐츠 삭제': 'Article 10. Account Termination and Content Deletion',
  '이용자는': 'Users may',
  '계정 삭제 안내': 'account deletion instructions',
  '에 따라 계정과 데이터를 삭제할 수 있습니다. 삭제된 콘텐츠는 복구할 수 없습니다.': 'to delete their account and data. Deleted content cannot be recovered.',
  '계정 삭제 시 서버의 계정·콘텐츠·생성 결과·인증 계정과 해당 기기의 계정별 로컬 데이터를 삭제합니다. 백업, 법령상 보존자료 및 외부 제공자의 잔여 로그는 제공자의 보관주기에 따라 즉시 삭제되지 않을 수 있습니다.':
    'When an account is deleted, the server account, content, generated results, authentication account, and account-specific local data on the device are deleted. Backups, records retained by law, and residual logs held by external providers may not be deleted immediately and are subject to the provider’s retention period.',
  '이용약관 위반, 보안 위협, 장기간 미사용으로 인한 운영상 필요 또는 법령상 요구가 있는 경우 운영자는 서비스 이용을 제한하거나 계정을 해지할 수 있습니다. 가능한 경우 사유를 안내합니다.':
    'The Operator may restrict Service use or terminate an account for a violation of these Terms, a security threat, operational necessity caused by prolonged inactivity, or a legal requirement. The reason will be explained where possible.',
  '제11조 이용자 통계와 개인정보': 'Article 11. User Statistics and Personal Information',
  '서비스는 선택적으로 PostHog를 이용하여 계정·이메일·메모 본문과 연결하지 않는 최소한의 이용 통계를 처리할 수 있습니다. 현재 자동수집, 페이지뷰, 페이지 이탈, 세션 녹화, 지속적인 브라우저·기기 식별자 저장 및':
    'The Service may optionally use PostHog to process minimal usage statistics that are not linked to accounts, email addresses, or memo content. It currently does not use automatic capture, pageviews, page exits, session recording, persistent browser or device identifiers, or ',
  '호출은 사용하지 않습니다. 자세한 사항은': ' calls. For details, see the ',
  '제12조 책임의 제한': 'Article 12. Limitation of Liability',
  '운영자는 무료 서비스의 특성상 서비스가 항상 중단 없이 제공되거나 모든 오류가 수정된다고 보장하지 않습니다.':
    'Because the Service is free, the Operator does not guarantee that it will always be provided without interruption or that every error will be corrected.',
  '이용자는 중요한 콘텐츠를 별도로 백업해야 하며, 계정 삭제·기기 고장·외부 서비스 장애·네트워크 문제로 인한 데이터 손실에 대비해야 합니다.':
    'Users must back up important content separately and prepare for data loss caused by account deletion, device failure, external-service outages, or network problems.',
  '운영자는 고의 또는 중대한 과실이 없는 한 관계 법령이 허용하는 범위에서 서비스 이용으로 발생한 간접적·특별한 손해에 대해 책임을 부담하지 않습니다. 이용자의 고의·과실로 발생한 손해, 법령 위반 또는 권리 침해에 대해서는 이용자가 책임을 질 수 있습니다.':
    'To the extent permitted by applicable law, the Operator is not liable for indirect or special damages arising from use of the Service unless caused by the Operator’s intent or gross negligence. Users may be responsible for damage caused by their intent or negligence, violations of law, or infringement of rights.',
  '이 조항은 소비자 보호, 개인정보 보호 및 그 밖에 관계 법령에서 제한할 수 없는 운영자의 책임을 제한하지 않습니다.':
    'This Article does not limit the Operator’s liability that cannot be limited under consumer-protection, privacy, or other applicable laws.',
  '제13조 약관의 변경': 'Article 13. Changes to the Terms',
  '이 약관은 2026년 8월 13일부터 적용되는 최초 시행 약관입니다. 운영자는 법령, 서비스 기능 또는 운영 방식의 변경에 따라 약관을 변경할 수 있습니다. 변경 내용과 시행일은 이 페이지에 게시하며, 이용자에게 중요한 변경은 로그인 화면, 앱 설정 또는 공지 등 이용자가 쉽게 확인할 수 있는 방법으로 안내합니다. 변경된 약관에 동의하지 않는 이용자는 계정을 삭제하고 서비스 이용을 중단할 수 있습니다.':
    'These are the initial Terms effective August 13, 2026. The Operator may change the Terms in response to changes in law, Service features, or operating methods. Changes and their effective date will be posted on this page, and material changes will be announced in a way users can easily see, such as the login screen, app settings, or an announcement. Users who do not agree to the changed Terms may delete their account and stop using the Service.',
  '제14조 준거법과 관할': 'Article 14. Governing Law and Jurisdiction',
  '이 약관에 정하지 않은 사항은 대한민국 관계 법령과 일반적인 관행에 따릅니다. 서비스 이용과 관련한 분쟁은 관계 법령에 따른 관할 법원에서 해결합니다.':
    'Matters not provided for in these Terms are governed by the applicable laws and generally accepted practices of the Republic of Korea. Disputes relating to use of the Service will be resolved by a court with jurisdiction under applicable law.',
  '제15조 문의': 'Article 15. Contact',
  '약관에 관한 문의는 운영자 오성훈에게': 'Questions about these Terms may be sent to the Operator, Oh Seonghun, at ',
  '으로 보내 주세요. 개인정보 관련 문의와 계정 삭제 요청은': '. Privacy questions and account deletion requests may be submitted using the method described in the ',
  '에 안내된 방법으로 접수할 수 있습니다.': '.',
});

export const accountDeletionTranslations = defineTranslations({
  'Subnota 계정과 계정에 연결된 서버 데이터 및 기기 내 로컬 데이터를 삭제할 수 있습니다. 삭제가 완료되면 계정과 콘텐츠를 복구할 수 없습니다.':
    'You can delete your Subnota account, server data linked to the account, and local data on your devices. Once deletion is complete, the account and content cannot be recovered.',
  '앱에서 삭제하기': 'Delete from the app',
  '데스크톱 앱': 'Desktop app',
  '설정 → 계정 → 계정 및 데이터 삭제를 선택합니다.': 'Select Settings → Account → Delete account and data.',
  ': 설정 → 계정 → 계정 및 데이터 삭제를 선택합니다.': ': Select Settings → Account → Delete account and data.',
  '모바일 앱': 'Mobile app',
  '노트 화면의 옵션 메뉴 → 계정 및 데이터 삭제를 선택합니다.': 'Select Options menu on the Note screen → Delete account and data.',
  ': 노트 화면의 옵션 메뉴 → 계정 및 데이터 삭제를 선택합니다.': ': Select Options menu on the Note screen → Delete account and data.',
  '확인 대화상자에서 삭제를 확정하면 인증 계정과 서버·기기 데이터가 삭제됩니다.':
    'Confirm the deletion in the confirmation dialog to delete the authentication account and server and device data.',
  '앱을 사용할 수 없는 경우': 'If you cannot use the app',
  '로그인에 사용한 이메일 주소로': 'Using the email address you used to sign in, request account deletion from ',
  '에 계정 삭제를 요청해 주세요. 요청에는 로그인 이메일을 적어 주세요. 본인 확인이 필요한 경우 추가 확인을 요청할 수 있습니다.':
    '. Include your sign-in email in the request. We may ask for additional verification if needed to confirm your identity.',
  '삭제되는 데이터': 'Data that will be deleted',
  'Supabase 인증 계정과 계정 프로필': 'The Supabase authentication account and account profile',
  '서버에 동기화된 메모, 일정, 수집함, 브리핑, 검색·토픽·임베딩 결과':
    'Memos, schedules, saved links, briefings, and search, topic, and embedding results synchronized to the server',
  '앱이 기기에 저장한 계정별 로컬 콘텐츠와 로컬 임베딩':
    'Account-specific local content and local embeddings stored on the device by the app',
  '법령상 보관이 필요한 자료, 보안 로그, 백업 또는 외부 처리 서비스의 잔여 로그는 관련 보관 기간과 제공자 정책에 따라 즉시 삭제되지 않을 수 있습니다. 자세한 내용은':
    'Records required to be retained by law, security logs, backups, or residual logs held by external processing services may not be deleted immediately and are subject to the relevant retention periods and provider policies. For details, see the ',
  '개인정보 처리방침': 'Privacy Policy',
  '확인해 주세요.': '.',
  '을 확인해 주세요.': '.',
});
