# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

simdjson_path = File.dirname(Pod::Executable.execute_command('node', ['-p',
  'const path = require("path");
   const watermelonPath = path.dirname(require.resolve("@nozbe/watermelondb/package.json", {paths: [process.argv[1]]}));
   require.resolve("@nozbe/simdjson/package.json", {paths: [watermelonPath]})', __dir__]).strip)

hermesc_path = File.join(File.dirname(Pod::Executable.execute_command('node', ['-p',
  'const path = require("path");
   const reactNativePath = path.dirname(require.resolve("react-native/package.json", {paths: [process.argv[1]]}));
   require.resolve("hermes-compiler/package.json", {paths: [reactNativePath]})', __dir__]).strip), 'hermesc/osx-bin/hermesc')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MemoApp' do
  config = use_native_modules!

  pod 'simdjson', :path => simdjson_path

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each do |config_name, xcconfig|
        xcconfig.attributes['HERMES_CLI_PATH'] = hermesc_path
        xcconfig.save_as(aggregate_target.xcconfig_path(config_name))
      end
    end
  end
end
