EMBEDDING_MODEL = "dragonkue/BGE-m3-ko"
EMBEDDING_BATCH_SIZE = 16

CHUNK_MIN_CHARS = 30
CHUNK_TARGET_CHARS = 180
CHUNK_MAX_CHARS = 350
CHUNK_MAX_SENTENCES = 3

TOPIC_MIN_MEMOS = 5
TOPIC_HDBSCAN_MIN_MEMOS = 30
TOPIC_HDBSCAN_MIN_CLUSTER_SIZE = 4
TOPIC_HDBSCAN_MIN_SAMPLES = 2
TOPIC_DISTANCE_THRESHOLD = 0.42
TOPIC_MAX_CLUSTERS = 12
TOPIC_LABEL_TERMS = 3

GEMINI_MODEL = "gemini-3.1-flash-lite"
