EMBEDDING_MODEL = "dragonkue/BGE-m3-ko"
EMBEDDING_BATCH_SIZE = 16

CHUNK_MIN_CHARS = 30
CHUNK_TARGET_CHARS = 180
CHUNK_MAX_CHARS = 350
CHUNK_MAX_SENTENCES = 3

NETWORK_QUERY_MAX_CHARS = 4_000
NETWORK_DEFAULT_MIN_SIMILARITY = 0.35

MEMO_CHUNK_SPLIT_MAX_CHARS = 20_000
NETWORK_CACHE_MAX_AGE_DAYS = 60
NETWORK_CACHE_MAX_ROWS_PER_USER = 500

TOPIC_MIN_MEMOS = 5
TOPIC_HDBSCAN_MIN_MEMOS = 30
TOPIC_HDBSCAN_MIN_CLUSTER_SIZE = 4
TOPIC_HDBSCAN_MIN_SAMPLES = 2
TOPIC_DISTANCE_THRESHOLD = 0.42
TOPIC_MAX_CLUSTERS = 12
TOPIC_LABEL_TERMS = 3
TOPIC_KEYWORD_CANDIDATES = 12
TOPIC_LLM_LABEL_MAX_CHARS = 12
TOPIC_LLM_LABEL_MAX_OUTPUT_TOKENS = 64
TOPIC_LLM_LABEL_TIMEOUT_MS = 10_000
TOPIC_MEMO_EDGE_TOP_K = 3
TOPIC_MEMO_EDGE_MIN_SIMILARITY = 0.35
# Saved inbox summaries attach to the nearest topic centroid at or above this.
TOPIC_INBOX_ATTACH_MIN_SIMILARITY = 0.45
TOPIC_MEMO_INBOX_EDGE_TOP_K = 2
TOPIC_MEMO_INBOX_EDGE_MIN_SIMILARITY = 0.35
MEMO_SIMILARITY_EDGE_TOP_K = 8
MEMO_SIMILARITY_EDGE_MIN_SIMILARITY = 0.38

MEMO_CHUNK_EDGE_TOP_K = 6
MEMO_CHUNK_EDGE_MIN_SIMILARITY = 0.35
MEMO_CHUNK_INDEX_LEASE_SECONDS = 900

GEMINI_MODEL = "gemini-3.1-flash-lite"
GEMMA_FALLBACK_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_FALLBACK_MODEL = "gemma-4-26b-a4b-it"
TOPIC_LABEL_MODELS = (GEMMA_TOPIC_LABEL_MODEL, GEMMA_TOPIC_LABEL_FALLBACK_MODEL)
SUMMARY_MODEL_FALLBACKS = (GEMINI_MODEL, GEMMA_FALLBACK_MODEL)
TEXT_SUMMARY_MODELS = (GEMMA_FALLBACK_MODEL, GEMINI_MODEL)
URL_CONTENT_SUMMARY_MODELS = (GEMINI_MODEL,)
