# Hugging Face serverless inference receives the model id, not a Hub revision.
# Keep the observed Hub commit in the cache signature so vectors from different
# model releases never mix; this is an audit label, not a runtime weight pin.
EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_MODEL_REVISION = "5617a9f61b028005a4858fdac845db406aefb181"
EMBEDDING_MODEL_SIGNATURE = f"{EMBEDDING_MODEL}@{EMBEDDING_MODEL_REVISION}"
EMBEDDING_BATCH_SIZE = 16

# 청킹 단위는 "한 문장 = 한 청크". 실제 경계는 줄바꿈이 정하고
# (build_network_chunks의 블록 규칙), 아래 값들은 줄바꿈 없이 길게 쓴 글에서만
# 작동하는 안전장치다. 한국어 문장 길이 연구값 기준으로 검증했다:
#   일상/구어 22.8~23.9자(6.5~7.3어절) · 문어/전문 58.6~60.5자(16.7~17.3어절)
#   → MAX_SENTENCES=3 은 일상 69자 / 문어 177자 ≈ TARGET_CHARS 와 맞는다.
#
# CHUNK_MIN_CHARS(짧으면 앞 청크와 병합)는 현재 한 번도 발동하지 않는다.
# 하한 30자가 한 문장(23자)보다 커서 모든 문장이 병합 대상이 되는데, 줄바꿈
# 블록 규칙이 전부 막기 때문이다. 실측: 병합 시도 280회, 발동 0회.
# 되살리지 말 것 — 줄을 넘어 병합하게 하면 무관한 주제가 한 벡터에 섞인다.
# (실제 사례: "리팩토링" + "내일 2시 축구"가 한 청크로 합쳐짐)
CHUNK_MIN_CHARS = 30
CHUNK_TARGET_CHARS = 180
CHUNK_MAX_CHARS = 350
CHUNK_MAX_SENTENCES = 3

MEMO_CHUNK_SPLIT_MAX_CHARS = 20_000
# State B embeds the current memo as one whole document, matching Topics.
NETWORK_QUERY_MAX_CHARS = MEMO_CHUNK_SPLIT_MAX_CHARS
NETWORK_DEFAULT_MIN_SIMILARITY = 0.35
NETWORK_CACHE_MAX_AGE_DAYS = 60
NETWORK_CACHE_MAX_ROWS_PER_USER = 500

TOPIC_MIN_MEMOS = 5
TOPIC_HDBSCAN_MIN_MEMOS = 30
TOPIC_HDBSCAN_MIN_CLUSTER_SIZE = 4
TOPIC_HDBSCAN_MIN_SAMPLES = 2
TOPIC_DISTANCE_THRESHOLD = 0.42
TOPIC_MAX_CLUSTERS = 12
TOPIC_LABEL_TERMS = 3
TOPIC_KEYWORD_CANDIDATES = 12
TOPIC_LLM_LABEL_MAX_CHARS = 12
TOPIC_LLM_LABEL_MAX_OUTPUT_TOKENS = 64
TOPIC_LLM_LABEL_TIMEOUT_MS = 10_000
TOPIC_MEMO_EDGE_TOP_K = 3
TOPIC_MEMO_EDGE_MIN_SIMILARITY = 0.35
# Saved inbox summaries attach to the nearest topic centroid at or above this.
TOPIC_INBOX_ATTACH_MIN_SIMILARITY = 0.45
TOPIC_MEMO_INBOX_EDGE_TOP_K = 2
TOPIC_MEMO_INBOX_EDGE_MIN_SIMILARITY = 0.35
MEMO_SIMILARITY_EDGE_TOP_K = 8
MEMO_SIMILARITY_EDGE_MIN_SIMILARITY = 0.38

MEMO_CHUNK_EDGE_TOP_K = 6
MEMO_CHUNK_EDGE_MIN_SIMILARITY = 0.35
MEMO_CHUNK_INDEX_LEASE_SECONDS = 900

GEMINI_MODEL = "gemini-3.1-flash-lite"
GEMMA_FALLBACK_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_FALLBACK_MODEL = "gemma-4-26b-a4b-it"
TOPIC_LABEL_MODELS = (GEMMA_TOPIC_LABEL_MODEL, GEMMA_TOPIC_LABEL_FALLBACK_MODEL)
SUMMARY_MODEL_FALLBACKS = (GEMINI_MODEL, GEMMA_FALLBACK_MODEL)
TEXT_SUMMARY_MODELS = (GEMMA_FALLBACK_MODEL, GEMINI_MODEL)
URL_CONTENT_SUMMARY_MODELS = (GEMINI_MODEL,)
