# Hugging Face serverless inference receives the model id, not a Hub revision.
# Keep the observed Hub commit in the cache signature so vectors from different
# model releases never mix; this is an audit label, not a runtime weight pin.
EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_MODEL_REVISION = "5617a9f61b028005a4858fdac845db406aefb181"
EMBEDDING_MODEL_SIGNATURE = f"{EMBEDDING_MODEL}@{EMBEDDING_MODEL_REVISION}"
EMBEDDING_BATCH_SIZE = 16

TOPIC_MIN_MEMOS = 5
TOPIC_LEIDEN_RESOLUTION = 1.0
TOPIC_LEIDEN_ITERATIONS = 2
TOPIC_LEIDEN_SEED = 0
TOPIC_INCREMENTAL_ATTACH_MIN_SCORE = 0.38
TOPIC_NEW_COMMUNITY_MIN_MEMOS = 2
TOPIC_MAX_CLUSTERS = 12
TOPIC_LABEL_TERMS = 3
TOPIC_KEYWORD_CANDIDATES = 12
TOPIC_LLM_LABEL_MAX_CHARS = 12
TOPIC_LLM_LABEL_MAX_OUTPUT_TOKENS = 64
TOPIC_LLM_LABEL_TIMEOUT_MS = 10_000
TOPIC_MEMO_EDGE_TOP_K = 3
TOPIC_MEMO_EDGE_MIN_SIMILARITY = 0.35
# Saved inbox summaries attach to the nearest topic centroid at or above this.
TOPIC_INBOX_ATTACH_MIN_SIMILARITY = 0.45
TOPIC_MEMO_INBOX_EDGE_TOP_K = 2
TOPIC_MEMO_INBOX_EDGE_MIN_SIMILARITY = 0.35
MEMO_SIMILARITY_EDGE_TOP_K = 8
MEMO_SIMILARITY_EDGE_MIN_SIMILARITY = 0.38

GEMINI_MODEL = "gemini-3.1-flash-lite"
GEMMA_FALLBACK_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_MODEL = "gemma-4-31b-it"
GEMMA_TOPIC_LABEL_FALLBACK_MODEL = "gemma-4-26b-a4b-it"
TOPIC_LABEL_MODELS = (GEMMA_TOPIC_LABEL_MODEL, GEMMA_TOPIC_LABEL_FALLBACK_MODEL)
SUMMARY_MODEL_FALLBACKS = (GEMINI_MODEL, GEMMA_FALLBACK_MODEL)
TEXT_SUMMARY_MODELS = (GEMMA_FALLBACK_MODEL, GEMINI_MODEL)
URL_CONTENT_SUMMARY_MODELS = (GEMINI_MODEL,)
